[build]
  # Directory to run build command from
  base = "frontend"
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

